apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: linkerd
  namespace: linkerd-system
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: linkerd
  chart:
    repository: https://helm.linkerd.io/stable
    name: linkerd2
    version: 2.8.1
  values:
    global:
      namespace: linkerd-system
    grafana:
      enabled: false
    tracing:
      enabled: false
