apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: tautulli
  namespace: media
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: tautulli
  chart:
    repository: https://k8s-at-home.com/charts/
    name: tautulli
    version: 3.0.0
  values:
    image:
      repository: linuxserver/tautulli
      tag: v2.5.4-ls12
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
    persistence:
      config:
        enabled: true
        existingClaim: nfs-configs
        subPath: tautulli
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.nginx: nginx
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: "letsencrypt-production"
      hosts:
        - plexpy.k3s.sharpe.wales
      tls:
        - secretName: plexpy-production-tls
          hosts:
            - plexpy.k3s.sharpe.wales
