apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: radarr
  chart:
    repository: https://bananaspliff.github.io/geek-charts
    name: radarr
    version: 0.1.0
  values:
    image:
      repository: linuxserver/radarr
      tag: 3.0.0.3502-ls21

    env:
      - name: PUID
        value: "1000"
      - name: PGID
        value: "1000"

    service:
      type: LoadBalancer
      port: 80

    volumes:
      - name: "radarr-downloads"
        persistentVolumeClaim:
          claimName: "nfs-downloads"
      - name: "radarr-movies"
        persistentVolumeClaim:
          claimName: "nfs-movies"
      - name: "radarr-config"
        persistentVolumeClaim:
          claimName: "nfs-configs"

    volumeMounts:
      - name: "radarr-config"
        mountPath: "/config"
        subPath: "radarr"
      - name: "radarr-downloads"
        mountPath: "/nfs-downloads"
      - name: "radarr-movies"
        mountPath: "/nfs-movies"
