apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: media
spec:
  type: ClusterIP
  ports:
    - port: 7878
      protocol: TCP
      name: http
  selector:
    app: radarr
    release: radarr
