apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-configs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.86.200
    path: "/nfs/Configs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-configs
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: nfs-configs
  storageClassName: ""
