apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: sonarr
  chart:
    repository: https://bananaspliff.github.io/geek-charts
    name: sonarr
    version: 0.1.0
  values:
    image:
      repository: linuxserver/sonarr
      tag: 3.0.3.911-ls39

    env:
      - name: PUID
        value: "1000"
      - name: PGID
        value: "1000"

    resources:
      requests:
        memory: 512Mi
        cpu: 0.5
      limits:
        memory: 1Gi
        cpu: 1

    service:
      type: LoadBalancer
      port: 80

    volumes:
      - name: "sonarr-downloads"
        persistentVolumeClaim:
          claimName: "nfs-downloads"
      - name: "sonarr-tvshows"
        persistentVolumeClaim:
          claimName: "nfs-tvshows"
      - name: "sonarr-config"
        persistentVolumeClaim:
          claimName: "nfs-configs"

    volumeMounts:
      - name: "sonarr-config"
        mountPath: "/config"
        subPath: "sonarr"
      - name: "sonarr-downloads"
        mountPath: "/nfs-downloads"
      - name: "sonarr-tvshows"
        mountPath: "/nfs-tvshows"
