apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-tvshows
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.86.200
    path: "/nfs/TVShows"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-tvshows
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: nfs-tvshows
  storageClassName: ""
