apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-tvshows
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.86.200
    path: "/nfs/TVShows"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-tvshows
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: nfs-tvshows
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-config
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /var/lib/rancher/k3s/storage/sonar-config
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-config
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: sonar-config
