apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-jackett
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.86.200
    path: "/nfs/Downloads/jackett"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-jackett
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "100Gi"
  volumeName: nfs-jackett
  storageClassName: ""
