apiVersion: v1
kind: Service
metadata:
  name: jackett
  namespace: media
spec:
  type: LoadBalancer
  loadBalancerIP: "192.168.86.175"
  ports:
    - port: 9117
      targetPort: 9117
      protocol: TCP
      name: http
  selector:
    app: jackett
    release: jackett
