apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: nginx-ingress
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: nginx-ingress
    version: 1.41.2
  values:
    defaultBackend:
      enabled: false
    controller:
      autoscaling:
        enabled: true
      service:
        externalTrafficPolicy: Local
      config:
        forwarded-for-header: "X-Forwarded-For"
        # enabled-real-ip: "true"
        log-format-upstream: '$remote_addr - $remote_user [$time_local] "$request" $ssl_protocol/$ssl_cipher $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_length $request_time [$proxy_upstream_name] [$proxy_alternative_upstream_name] $upstream_addr $upstream_response_length $upstream_response_time $upstream_status $req_id'
        ssl-redirect: "true"
        force-ssl-redirect: "true"
        # use-proxy-protocol: "true"
        # proxy-real-ip-cidr: "10.42.0.0/16"
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
        # prometheusRule:
        #   enabled: true
        #   namespace: monitoring
