apiVersion: v1
kind: Service
metadata:
  namespace: wikijs
  name: postgresql
  labels:
    app: postgresql
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
  selector:
    app: postgresql
