apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: openfaas
  namespace: openfaas
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: openfaas
  chart:
    repository: https://openfaas.github.io/faas-netes/
    name: openfaas
    version: 6.0.1
  values:
    functionNamespace: openfaas-fn
    ingress:
      enabled: true
      hosts:
        - host: gateway.k3s.sharpe.wales
          serviceName: gateway
          servicePort: 8080
          path: "/"
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: "letsencrypt-production"
      tls:
        - secretName: openfaas-production-tls
          hosts:
            - gateway.k3s.sharpe.wales
    prometheus:
      create: false
    alertmanager:
      create: false

