apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: transmission
  namespace: media-transmission
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: transmission
  chart:
    repository: https://bananaspliff.github.io/geek-charts
    name: transmission-openvpn
    version: 0.1.0
  values:
    image:
      repository: "haugene/transmission-openvpn"
      tag: "2.13"
      pullPolicy: "IfNotPresent"

    env:
    - name: OPENVPN_PROVIDER
      value: "MULLVAD"
    - name: OPENVPN_CONFIG
      value: "mullvad_se-sto-tcp443"
    - name: OPENVPN_USERNAME
      valueFrom:
        secretKeyRef:
          name: transmission-credentials
          key: username
    - name: OPENVPN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: transmission-credentials
          key: password
    - name: LOCAL_NETWORK
      value: "192.168.86.0/24"
    - name: WEBPROXY_ENABLED
      value: "false"
    - name: TRANSMISSION_WEB_UI
      value: "transmission-web-control"
    - name: TRANSMISSION_DOWNLOAD_DIR
      value: "/nfs-downloads/complete"
    - name: TRANSMISSION_INCOMPLETE_DIR_ENABLED
      value: "true"
    - name: TRANSMISSION_INCOMPLETE_DIR
      value: "/nfs-downloads/incomplete"
    - name: TRANSMISSION_RATIO_LIMIT
      value: "0.01"
    - name: TRANSMISSION_RATIO_LIMIT_ENABLED
      value: "true"
    - name: TRANSMISSION_ALT_SPEED_DOWN
      value: "1000"
    - name: TRANSMISSION_ALT_SPEED_UP
      value: "200"
    - name: TRANSMISSION_ALT_SPEED_TIME_ENABLED
      value: "true"
    - name: TRANSMISSION_ALT_SPEED_TIME_DAY
      value: "62"
    - name: TRANSMISSION_ALT_SPEED_TIME_BEGIN
      value: "420"
    - name: TRANSMISSION_ALT_SPEED_TIME_END
      value: "1380"
    - name: TRANSMISSION_BLOCKLIST_ENABLED
      value: "true"
    # - name: TRANSMISSION_BLOCKLIST_URL
    #   name: "http://john.bitsurge.net/public/biglist.p2p.gz"

    volumes:
      - name: "transmission"
        persistentVolumeClaim:
          claimName: "nfs-transmission"
      - name: "dev-tun"
        hostPath:
          path: "/dev/net/tun"
    volumeMounts:
      - name: "transmission"
        mountPath: "/nfs-downloads"
      - name: "dev-tun"
        mountPath: "/dev/net/tun"

    securityContext:
      capabilities:
        add:
          - NET_ADMIN
