apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-transmission
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.86.200
    path: "/nfs/Downloads"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "nfs-transmission"
  namespace: "media-transmission"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "100Gi"
  volumeName: nfs-transmission
  storageClassName: ""
