apiVersion: v1
kind: Service
metadata:
  name: transmission-transmission-openvpn
  namespace: media
spec:
  type: LoadBalancer
  loadBalancerIP: "192.168.86.172"
  ports:
    - port: 9191
      targetPort: 9091
      protocol: TCP
      name: http
  selector:
    app: transmission-openvpn
    release: transmission
