apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: metallb
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: metallb
    version: 0.12.0
  values:
    configInline:
      address-pools:
        - name: default
          protocol: bgp
          addresses:
            - 192.168.86.170-192.168.86.180

