apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: pihole
  chart:
    repository: https://mojo2600.github.io/pihole-kubernetes/
    name: pihole
    version: 1.7.14
  values:
    persistentVolumeClaim:
      enabled: true

    admin:
      existingSecret: "pihole-credentials"
      passwordKey: "admin-password"

    extraEnvVars:
      TZ: "Europe/London"
      ServerIP: 192.168.86.169

    serviceTCP:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc

    serviceUDP:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc

    DNS1: "1.1.1.1"
    DNS2: "8.8.8.8"

    dnsmasq:
      customDnsEntries:
        - address=/pihole.local/192.168.86.171
        - address=/plex.local/192.168.86.201
        - address=/proxmox.local/192.168.86.200
