apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: pihole
  chart:
    repository: https://mojo2600.github.io/pihole-kubernetes/
    name: pihole
    version: 1.7.14
  values:
    persistentVolumeClaim:
      enabled: true

    admin:
      existingSecret: "pihole-credentials"
      passwordKey: "admin-password"

    extraEnvVars:
      TZ: "Europe/London"
      ServerIP: 192.168.86.169

    serviceTCP:
      type: LoadBalancer
      loadBalancerIP: "192.168.86.172"
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc

    serviceUDP:
      type: LoadBalancer
      loadBalancerIP: "192.168.86.172"
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc

    DNS1: "1.1.1.1"
    DNS2: "8.8.8.8"

    dnsmasq:
      additionalHostsEntries:
        - 192.168.86.171 pihole
        - 192.168.86.200 prox
        - 192.168.86.201 plex
        - 192.168.86.172 transmission
        - 192.168.86.173 radarr
        - 192.168.86.174 sonarr

    webHttp: "8080"
    webHttps: "8443"
