apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-credentials
  namespace: pihole
spec:
  encryptedData:
    admin-password: AgAKU4H80yzMN80JH4G89lwDSt4AXtx2MuSbSsszKiXCtCxO4bozsdP8iJpbZpgr4kdM68ssJnolZZjvuAGFQBDoX8LlIQge/kZhUf/HfGSOkzlUZ3dU0UJaakXTsQj8zfNl6HY/WoZ3wsih/YfpSOfcQDLn8zQax+xsuU4CwLFIBv34qssecWtfBJWzHhnyy8ElBLSMVaDGXMSedZ10F6EkL+B42wUE6lbuaNk5yroIQLHLXwLIegmSarWidO2zILJTtn2tjjf5cWtezC3Hb29yEZ+ea0QmOf+OjzPcYGCDpq91x8HXb1qj0RTDhp4Be0k9rSk7sOgOfMEcXNlhQyY6yCjaq9wD5gntv49/ydCyC42cikdP0Hz/mqZeNsUJW8A4tkRZ4/te6Kol2Kdpc1kUMGr3FLskI8kgvPGgkCMHwzcYWoa3Hj9uNqwSDE/PX7Hb3J5hjg0gRo/uxLrIahrp8G0Zlulft+BcNvR5Sv5G2mAMu/wBnbzJFnYqlaqdzJpd4DJYUv8IRvq2ZRQoKSZk5NLpo+PQ/DdCUwRqp7hzNqEHVRoiN4qy94pRdw7zAuIx8mcBLKJkm+2BjxqDN0YK3MTS6RGrAI2GfjLB0gvGPaLiKTZRbtvAQUKHPKgCIRFBON0UmqjRQLxD8X2xG+9TX/XAEF9RwOwU83GySNDLHaBReYch9Ok1UZts19TZPV4kWzo9RYj+wCBuKVxWFCyQyrP4d++/gk4XbXhnEiY=
