apiVersion: v1
kind: ConfigMap
metadata:
  name: ip-updater
  namespace: kube-system
data:
  update-ip.sh: |-
    #!/bin/bash

    # Grab my current IP address
    CURRENT_IP=$(curl -s ifconfig.co)
    # Check what my domain-name is set to
    HOSTED_ZONE_ID=$(aws route53 list-hosted-zones-by-name | \
      jq --arg name "$ROUTE53_DOMAIN" \
      -r '.HostedZones | .[] | select(.Name=="\($name)") | .Id' \
      | cut -d/ -f 3)

    CURRENT_CNAME_VALUE=$(aws route53 list-resource-record-sets \
      --hosted-zone-id $HOSTED_ZONE_ID | \
      jq --arg name "k3s.$ROUTE53_DOMAIN" -r \
      '.ResourceRecordSets | .[] | select(.Name=="\($name)") | .ResourceRecords[].Value')

    if [ $CURRENT_IP == $CURRENT_CNAME_VALUE ];
    then
      echo "Current IP set in HostedZone is the same as HomeIP"
      echo "Nothing to do..."
    else
      echo "Changing now..."
      cat >/tmp/new-record.json <<EOL
    {
      "Comment": "Updating HomeIP via Kubernetes CronJob",
      "Changes": [
        {
          "Action": "UPSERT",
          "ResourceRecordSet": {
            "Name": "k3s.$ROUTE53_DOMAIN",
            "Type": "A",
            "TTL": 60,
            "ResourceRecords": [
                {
                  "Value": "$CURRENT_IP"
                }
              ]
            }
        }
      ]
    }
    EOL
      aws route53 change-resource-record-sets \
        --hosted-zone-id $HOSTED_ZONE_ID \
        --change-batch file:///tmp/new-record.json > /dev/null
      echo "Updated from $CURRENT_CNAME_VALUE to $CURRENT_IP"
    fi
