apiVersion: v1
kind: Service
metadata:
  name: bazarr
  namespace: media
spec:
  type: LoadBalancer
  loadBalancerIP: "192.168.86.177"
  ports:
    - port: 6767
      targetPort: 6767
      protocol: TCP
      name: http
  selector:
    app: bazarr
    release: bazarr
