# As the prom-postgres-exporter cannot helm chart isn't able to
# look across namespaces for the secret this will have to do
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: monitoring
spec:
  encryptedData:
    postgresql-password: AgAoP3YDffR2kULgrqdF6W5rhPx26M0/iU348+h3b6KjEWY8STgoXNoXHWBWqgmUBjAFVagqYncQjqoSqlYuAMrAntwJxdwFFc2QPeBiAcOIHkocrgz1rkhCWYZrbXFAHk72UIbnymPFntwqi2D4VnWMwwgjsZHh+890t90QlzqIpoZdqZkhK2knsiuYIz0yxIisTLrg+bQQGfVrscPpCZnGmWrxmJX8BGbK1cmxnwrPDJpEKE+TdqHmECe2OcDTBq5FBMPwiEBjoY9+tV7aJkI56ArmbNabu94wKrILhtOoLiIL/Ra3Kw1b3Bhw5T+HOBoNQt6X3cuxlfaRZaRyXX1Rvk4zcZvdD30vZvG/lCrOPUImLCScfk0tsmsoqJGm65nPaXLGA1Hlw0sJTd/f+HCfL3MkpTirSh2YPOq8/GlZaJG775Ni1TAF3XxITB9sM5uGkPRnY0oWulAoqXVeM106Wk36Zstn2PVO7Xiixuejm92WJ5+BeSn5MLnEZEw1dZcXx4b3pNX1eM8ava/HAkmrnO5ZkyjhTpv8GSn2xH8yTKVdlPPejtIOEbLDWNACOKFCYiVyHqNOMyViZk477YEccusMZLb8B+wmoOuqbXaGar4SG97IgyfOBpCC3XS+olyQl90SOqdGOu/dRiXQ21/xra+gW7erkTeGcFunfAizua+R+THHC5gbz9RsjlLgEIFNppVBVOv1/sj2VA1bmlm1E+p8bhKiuajBBfw2/Re4Wpxtpt5zMA7HNp5dZDxb6SDvHTlBkK5NmSvvn90=
