apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: prometheus-operator
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: prometheus-operator
    version: 9.3.1
  values:
    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
        # additionalScrapConfigs:
    alertmanager:
      enabled: false
    grafana:
      enabled: true
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.nginx: nginx
          kubernetes.io/tls-acme: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - grafana.k3s.sharpe.wales
        tls:
          - secretName: grafana-production-tls
            hosts:
              - grafana.k3s.sharpe.wales
      admin:
        existingSecret: grafana-credentials
      sidecar:
        datasources:
            enabled: true
    kubeEtcd:
      enabled: false
