apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: prometheus-operator
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: prometheus-operator
    version: 9.3.1
  values:
    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
        # additionalScrapConfigs:
    alertmanager:
      enabled: false
    grafana:
      enabled: true
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.nginx: nginx
          kubernetes.io/tls-acme: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - grafana.k3s.sharpe.wales
        tls:
          - secretName: grafana-production-tls
            hosts:
              - grafana.k3s.sharpe.wales
      admin:
        existingSecret: grafana-credentials
      additionalDataSources:
        - name: Linkerd
          type: prometheus
          url: http://linkerd-prometheus.linkerd:9090
          access: proxy
          isDefault: false
        - name: Postgres
          type: prometheus
          url: http://prometheus-postgres-exporter:80
          access: proxy
          isDefault: false
        - name: Openfaas
          type: prometheus
          url: http://prometheus.openfaas:9090
          access: proxy
          isDefault: false
      # sidecar:
      #   datasources:
      #       enabled: true
      # Grabbing the public dashboards (by id)
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
          - name: "nginx"
            orgId: 1
            folder: "Nginx"
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/nginx
          - name: "Linkerd"
            orgId: 1
            folder: "Linkerd"
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/linkerd
          - name: "postgres"
            orgId: 1
            folder: "Postgres"
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/postgres
          - name: "default"
            orgId: 1
            folder: ""
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
      dashboards:
        default:
          kubernetes-cluster:
            datasource: Prometheus
            gnetId: 7249
          kubernetes-cluster01:
            datasource: Prometheus
            gnetId: 10000
        postgres:
          postgres-exporter:
            datasource: Postgres
            gnetId: 3742
        nginx:
          nginx-ingress-controller:
            datasource: Prometheus
            gnetId: 9614
        linkerd:
          authority:
            url: https://raw.githubusercontent.com/linkerd/linkerd2/main/grafana/dashboards/authority.json
            folder: "Linkerd"
            datasource: Linkerd
          cronjob:
            url: https://raw.githubusercontent.com/linkerd/linkerd2/main/grafana/dashboards/cronjob.json
            folder: "Linkerd"
            datasource: Linkerd
          daemonset:
            url: https://raw.githubusercontent.com/linkerd/linkerd2/main/grafana/dashboards/daemonset.json
            folder: "Linkerd"
            datasource: Linkerd
          grafana:
            url: https://raw.githubusercontent.com/linkerd/linkerd2/main/grafana/dashboards/grafana.json
            folder: "Linkerd"
            datasource: Linkerd
          health:
            url: https://raw.githubusercontent.com/linkerd/linkerd2/main/grafana/dashboards/health.json
            folder: "Linkerd"
            datasource: Linkerd
          job:
            url: https://raw.githubusercontent.com/linkerd/linkerd2/main/grafana/dashboards/job.json
            folder: "Linkerd"
            datasource: Linkerd
          kubernetes:
            url: https://raw.githubusercontent.com/linkerd/linkerd2/main/grafana/dashboards/kubernetes.json
            folder: "Linkerd"
            datasource: Linkerd
          multicluster:
            url: https://raw.githubusercontent.com/linkerd/linkerd2/main/grafana/dashboards/multicluster.json
            folder: "Linkerd"
            datasource: Linkerd
          namespace:
            url: https://raw.githubusercontent.com/linkerd/linkerd2/main/grafana/dashboards/namespace.json
            folder: "Linkerd"
            datasource: Linkerd
          pod:
            url: https://raw.githubusercontent.com/linkerd/linkerd2/main/grafana/dashboards/pod.json
            folder: "Linkerd"
            datasource: Linkerd
          prometheus-benchmark:
            url: https://raw.githubusercontent.com/linkerd/linkerd2/main/grafana/dashboards/prometheus-benchmark.json
            folder: "Linkerd"
            datasource: Linkerd
          prometheus:
            url: https://raw.githubusercontent.com/linkerd/linkerd2/main/grafana/dashboards/prometheus.json
            folder: "Linkerd"
            datasource: Linkerd
          replicaset:
            url: https://raw.githubusercontent.com/linkerd/linkerd2/main/grafana/dashboards/replicaset.json
            folder: "Linkerd"
            datasource: Linkerd
          replicationcontroller:
            url: https://raw.githubusercontent.com/linkerd/linkerd2/main/grafana/dashboards/replicationcontroller.json
            folder: "Linkerd"
            datasource: Linkerd
          route:
            url: https://raw.githubusercontent.com/linkerd/linkerd2/main/grafana/dashboards/route.json
            folder: "Linkerd"
            datasource: Linkerd
          service:
            url: https://raw.githubusercontent.com/linkerd/linkerd2/main/grafana/dashboards/service.json
            folder: "Linkerd"
            datasource: Linkerd
          statefulset:
            url: https://raw.githubusercontent.com/linkerd/linkerd2/main/grafana/dashboards/statefulset.json
            folder: "Linkerd"
            datasource: Linkerd
          top-line:
            url: https://raw.githubusercontent.com/linkerd/linkerd2/main/grafana/dashboards/top-line.json
            folder: "Linkerd"
            datasource: Linkerd
    kubeEtcd:
      enabled: false
