apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: prometheus-operator
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: prometheus-operator
    version: 9.3.1
  values:
    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
        # additionalScrapConfigs:
    alertmanager:
      enabled: false
    grafana:
      enabled: true
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.nginx: nginx
          kubernetes.io/tls-acme: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - grafana.k3s.sharpe.wales
        tls:
          - secretName: grafana-production-tls
            hosts:
              - grafana.k3s.sharpe.wales
      admin:
        existingSecret: grafana-credentials
      additionalDataSources:
        - name: Linkerd
          type: prometheus
          url: http://linkerd-prometheus.linkerd:9090
          access: proxy
          isDefault: false
      # sidecar:
      #   datasources:
      #       enabled: true
      # Grabbing the public dashboards (by id)
      dashboardProviders:
        dashboardsproviders.yaml:
          apiVersion: 1
          providers:
          - name: "nginx"
            orgId: 1
            folder: "Nginx"
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/nginx
          - name: "Linkerd"
            orgId: 1
            folder: "Linkerd"
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/linkerd
      dashboards:
        nginx:
          nginx-ingress-controller:
            datasource: Prometheus
            gnetId: 9614
            revision: 2
        linkerd:
          pod:
            url: https://raw.githubusercontent.com/linkerd/linkerd2/main/grafana/dashboards/pod.json
            folder: "Linkerd"
            datasource: Linkerd
    kubeEtcd:
      enabled: false
